name: pawsure_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    
  # Networking
  http: ^1.1.0
  supabase_flutter: ^2.5.3

  # State Management
  get: ^4.7.2

# UI & Utilities
  table_calendar: ^3.0.0
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  google_fonts: ^5.0.0
  lucide_icons: ^0.257.0
  intl: ^0.20.2

  # Storage
  shared_preferences: ^2.5.4

  # To pick files from the device
  file_picker: ^10.3.3

  # Maps & Charts
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  fl_chart: ^0.69.2

  # display media
  carousel_slider: ^5.0.0

  # message
  socket_io_client: ^2.0.3+1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/