name: pawsure_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    
  # Networking
  http: ^1.1.0

  # State Management
  get: ^4.7.2

  # UI & Utilities
  table_calendar: ^3.0.0
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  google_fonts: ^5.0.0
  lucide_icons: ^0.257.0
  intl: ^0.20.2

  # Storage
  shared_preferences: ^2.5.3
  
  # Supabase
  supabase_flutter: ^2.8.0

  # To pick files from the device
  file_picker: ^10.3.3

  # URL Launcher for phone calls and maps
  url_launcher: ^6.2.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/